# The Docker image to run your workspace in.
image:
  file: .gitpod.dockerfile

# Commands on:
tasks:
  # workspace initialization
  - init: >
      pip3 install --upgrade pip &&
      pip3 install -r requirements.txt
  # workspace startup  
    command: > 
      echo 'alias pip="pip3"' >> ~/.bashrc &&
      echo 'alias python="python3"' >> ~/.bashrc &&
      source ~/.bashrc
# Ports to expose
ports:
  - port: 8080

# Install vscode extensions
vscode:
  extensions:
    - formulahendry.auto-close-tag@0.5.6:oZ/8R2VhZEhkHsoeO57hSw==
    - mkaufman.HTMLHint@0.6.0:TdNYbCmjW8N3yiaPW4/adg==
    - ms-python.python@2019.8.30787:TnGEOx35GXMhyKLjDGz9Aw==
